### ISSUE TITLE
Compatibility matrix is incorrect

### ISSUE THREAD

**Issue by ghost** [DoD-Platform-One/Keycloak-P1-Auth-Plugin#2]
The [compatibility matrix](https://repo1.dso.mil/big-bang/product/plugins/keycloak-p1-auth-plugin/-/blob/main/docs/compatibility-matrix.md) indicates plugin version `3.2.1` is compatible with Keycloak version `21.0.2`. We are in the process of upgrading to BigBang `1.57.1` and found this was inaccurate. Neither `3.2.1` nor the plugin version used with the previous BigBang Keycloak version (plugin `3.0.0`) work with Keycloak `21.0.2`. Plugin version `3.2.0` IS compatible with Keycloak `21.0.2`.

If we try to use plugin `3.2.1` with Keycloak `21.0.2`, clicking the self-register link instantly fails with an internal server error (500). Keycloak logs show a message like:
```
ERROR...KeycloakErrorHandler...Uncaught server error...NoSuchMethodError...getHttpRequest()...
```

UPDATE: The compatibility matrix IS incorrect, but the solution I suggested at first above is not right. Rather than removing the compatibility, the issues should be corrected. See sister issue https://repo1.dso.mil/big-bang/product/plugins/keycloak-p1-auth-plugin/-/issues/36
